docs/OAP-Installation-Guide.md
docs/User-Guide.md

Add User-Guide.md
Fix: #3 
N/A

[OAP-MLlib-3]Add User-Guide.md

---

third-party-programs-oneCCL.txt

Update third-party-programs-oneCCL.txt
Fix: #15 
N/A

[ML-15]Update third-party-programs-oneCCL.txt

---

.github/PULL_REQUEST_TEMPLATE

[ML-21] Update PULL_REQUEST_TEMPLATE

---

dev/test-cluster/config-ssh.sh
dev/test-cluster/core-site.xml
dev/test-cluster/envs.sh
dev/test-cluster/hadoop-env.sh
dev/test-cluster/hdfs-site.xml
dev/test-cluster/setup-cluster.sh
dev/test-cluster/setup-python3-env.sh
dev/test-cluster/spark-defaults.conf
dev/test-cluster/workloads/kmeans-pyspark.py
dev/test-cluster/workloads/run-kmeans-pyspark.sh
dev/test-cluster/yarn-site.xml
mllib-dal/test-cluster.sh

[ML-12] Improve CI and add pseudo cluster testing

---

README.md

[ML-23] Add OAP MLlib Specific Configuration to README

---

README.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md
docs/index.md

Update the Readme about spark config.

[ML-23]Backport master Readme to branch-1.1

---

CHANGELOG.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
mkdocs.yml

[ML-71]Update documents for OAP 1.1.1

---

README.md
docs/OAP-Developer-Guide.md
docs/User-Guide.md
docs/index.md

Modify the OAP version,  and refine developer guide.

[ML-71]Update documents for OAP MLlib 1.1.1

---

mllib-dal/src/spark-3.0.1/main/scala/org/apache/spark/ml/classification/NaiveBayes.scala
mllib-dal/src/spark-3.0.2/main/scala/org/apache/spark/ml/classification/NaiveBayes.scala
mllib-dal/src/spark-3.1.1/main/scala/org/apache/spark/ml/classification/NaiveBayes.scala

[ML-86][NaiveBayes] Fix isOAPEnabled and add multi-version support

---

examples/als/pom.xml
examples/kmeans/pom.xml
examples/linear-regression/pom.xml
examples/naive-bayes/pom.xml
examples/pca/pom.xml
mllib-dal/pom.xml

[ML-91]Update the version in pom.xml

---

README.md

[ML-97][DOC] Add instructions for Standalone mode

---

README.md

[ML-85][Doc] Add explanation for spark.shuffle.reduceLocality.enabled 

---

mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java

[ML-105][Core] Fix crash when libfabric version conflict

---

mllib-dal/pom.xml
mllib-dal/src/assembly/assembly.xml
mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java

[ML-114] [Core] Improve native lib loading

---

mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
mllib-dal/src/main/scala/org/apache/spark/ml/clustering/KMeansDALImpl.scala
mllib-dal/src/main/scala/org/apache/spark/ml/feature/PCADALImpl.scala
mllib-dal/src/main/scala/org/apache/spark/ml/recommendation/ALSDALImpl.scala
mllib-dal/src/main/scala/org/apache/spark/ml/util/OneCCL.scala
mllib-dal/src/main/scala/org/apache/spark/ml/util/OneDAL.scala
mllib-dal/src/main/scala/org/apache/spark/ml/util/Utils.scala

closes #123 #122 #120 #121 #119

[ML-123][Core] Improve locality handling for native lib loading

---

CHANGELOG.md
README.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/User-Guide.md
docs/index.md
mkdocs.yml

Update Changelog and OAP guide

[ML-128] Update Changelog and OAP guide

---

README.md
docs/User-Guide.md
docs/index.md

[ML-128] Update OAP guide

---

mllib-dal/src/assembly/assembly-cpu-gpu.xml
mllib-dal/src/main/native/GPU.cpp
mllib-dal/src/main/native/Makefile

[ML-125][GPU] Update for Kmeans and PCA

---

examples/als/pom.xml
examples/correlation/pom.xml
examples/kmeans-pyspark/run.sh
examples/kmeans/pom.xml
examples/linear-regression/pom.xml
examples/naive-bayes/pom.xml
examples/pca/pom.xml
examples/summarizer/pom.xml
mllib-dal/pom.xml

closes #155 
- CI
- Example
No

[ML-155] [POM] Update scala version to 2.12.15

---

mllib-dal/src/main/native/KMeansDALImpl.cpp
mllib-dal/src/main/native/PCADALImpl.cpp

[GPU] Add convertToSyclHomogen for row merged table for kmeans and pca

---

README.md

[ML-165] Update README.md

---

examples/linear-regression/src/main/scala/org/apache/spark/examples/ml/LinearRegressionExample.scala
examples/naive-bayes/src/main/scala/org/apache/spark/examples/ml/NaiveBayesExample.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/OneDAL.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/classification/NaiveBayesDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/regression/LinearRegressionDALImpl.scala
mllib-dal/src/main/scala/org/apache/spark/ml/classification/spark320/NaiveBayes.scala
mllib-dal/src/main/scala/org/apache/spark/ml/regression/spark312/LinearRegression.scala
mllib-dal/src/main/scala/org/apache/spark/ml/regression/spark320/LinearRegression.scala
mllib-dal/src/test/scala/org/apache/spark/ml/classification/MLlibNaiveBayesSuite.scala
mllib-dal/src/test/scala/org/apache/spark/ml/regression/MLlibLinearRegressionSuite.scala

Signed-off-by: minmingzhu <minming.zhu@intel.com>
Use feature column instead of "features"
- CI
- Example

[ML-163] use feature column instead of "features"

---

README.md

Update Readme's tarball link
- CI
- Example
No

[ML-172] Update Readme's tarball link

---

README.md

Update Readme's tarball link
- CI
- Example
No

[ML-172] Update Readme's tarball link (#173)

---

CHANGELOG.md
README.md
TPP.txt
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/index.md
mkdocs.yml
third-party-programs-oneCCL.txt
third-party-programs-oneDAL.txt

Update Changelog, TPP and README for OAP 1.3.1
- CI
- Example
No.

[ML-172] Update documentation for OAP 1.3.1

---

CHANGELOG.md
README.md
TPP.txt
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/index.md
mkdocs.yml

Update Changelog and documents for OAP 1.4.0.
- CI
- Example
No.

[ML-172] Update documentation for OAP 1.4.0

---

mllib-dal/pom.xml

Signed-off-by: minmingzhu <minming.zhu@intel.com>
(Please fill in changes proposed in this fix)
- CI
- Example
No.

update junit to the latest

---

CHANGELOG.md
README.md
docs/OAP-Developer-Guide.md
docs/OAP-Installation-Guide.md
docs/index.md
mkdocs.yml

Update documents for OAP 1.5.0

[ML-172] Update documents for OAP 1.5.0

---

1.5.0/OAP-Developer-Guide/index.html
1.5.0/OAP-Installation-Guide/index.html
latest/OAP-Developer-Guide/index.html
latest/OAP-Installation-Guide/index.html

Modify docs website version selector for OAP 1.5.0

Modify docs website version selector for OAP 1.5.0

---

mllib-dal/src/test/scala/com/intel/oap/mllib/SummarizerHomogenTableSuite.scala

[ML-263] [Summarizer] Fix read data path error

---

mllib-dal/src/main/native/build-jni.sh

[ML-275] Fix jni error because of wrong class name

---

README.md

closes #270
(Please fill in changes proposed in this fix)

[ML-270] Update README

---

examples/scala/summarizer-scala/run-cpu.sh
examples/scala/summarizer-scala/run-gpu.sh

[ML-313] Solve Summarizer example script path error

---

examples/python/random-forest-regressor-pyspark/random_forest_regressor_example.py

[ML-314] Solve RF regression example error that lack of import.

---

examples/python/pca-pyspark/pca-pyspark.py
examples/python/pca-pyspark/run-cpu.sh
examples/python/pca-pyspark/run-gpu.sh
examples/scala/pca-scala/run-cpu.sh

[ML-328] fix pca example python script bug

---

.github/workflows/ci-tests.yml
mllib-dal/src/main/java/com/intel/oap/mllib/feature/PCAResult.java
mllib-dal/src/main/native/OneCCL.cpp
mllib-dal/src/main/native/service.cpp

[ML-335] Fix issues

---

mllib-dal/src/main/scala/com/intel/oap/mllib/Utils.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/classification/RandomForestClassifierDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/clustering/KMeansDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/feature/PCADALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/regression/LinearRegressionDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/regression/RandomForestRegressorDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/stat/CorrelationDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/stat/SummarizerDALImpl.scala

[ML-340] Make log output the specific path to support automatic generate result.

---

mllib-dal/src/main/scala/com/intel/oap/mllib/Utils.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/classification/RandomForestClassifierDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/clustering/KMeansDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/feature/PCADALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/regression/RandomForestRegressorDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/stat/CorrelationDALImpl.scala
mllib-dal/src/main/scala/com/intel/oap/mllib/stat/SummarizerDALImpl.scala

[ML-346] Subdivide the current training time into oneccl init time and onedal training time

---

examples/scala/pom-parent.xml
mllib-dal/pom.xml

[ML-349] fix cve issues
